### ISSUE TITLE
The extension stopped working in update to 5.28 under Wordpress

### ISSUE THREAD

**Issue by r4zoli** [agiliway/com.agiliway.civicalendar#25]
I updated my WP site to 5.28 from 5.27.3, and the extension throws errors: 
***ERROR***
message:            civicalendar_scroll_time,civicalendar_default_view,civicalendar_time_format,civicalendar_hide_past_events not valid settings
code:               
exception:          CiviCRM_API3_Exception Object
(
    [extraParams:CiviCRM_API3_Exception:private] => Array
        (
            [error_code] => 0
            [entity] => Setting
            [action] => get
            [is_error] => 1
            [error_message] => civicalendar_scroll_time,civicalendar_default_view,civicalendar_time_format,civicalendar_hide_past_events not valid settings.
And stopped working.

**Comment by taraskyliievych** [comment]
I advise you to try, turn off and uninstall calendar, and then install again. There may be a problem when you upgrade Wordpress.

**Comment by r4zoli** [comment]
Thanks. Now working again.
